config/routes.rb
Rails.application.routes.draw do
  root "skins#new"

  devise_for :users, controllers: {sessions: "sessions"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "about", to: "static#about", as: "about"
  get "faq", to: "static#faq", as: "faq"
  get "contact", to: "static#contact", as: "contact"
  get "donate", to: "static#donate", as: "donate"
  post "contact", to: "static#send_message", as: "send_message"
  get "open-letter", to: "static#open_letter"
  get "open_letter", to: redirect("open-letter")
  get "rules", to: "static#rules"
  get "sitemap", to: "static#sitemap", defaults: {format: "xml"}

  # Gallery Routes
  get "gallery/banners", to: "banners#index", as: "banners_gallery"
  get "gallery/banners/:page", to: "banners#index"
  get "gallery/skins", to: "skins#index", as: "skins_gallery"
  get "gallery/skins/:page", to: "skins#index"
  get "gallery", to: redirect(path: "/gallery/skins")
  get "gallery/:page", to: redirect("/gallery/skins/%{page}")

  get "jam/:jam", to: redirect("/gallery/skins/?tag=%{jam}")

  get "skins", to: redirect("/gallery/skins")
  get "skins/random", to: "skins#random", as: "random_skin"
  get "skins/:id/download", to: "skins#download", as: "skin_download"
  get "skins/:id/texture", to: "skins#texture", as: "skin_texture"
  get "skins/:id/social", to: "skins#social", as: "skin_social"
  get "skins/:id/embed", to: "skins#embed", as: "skin_embed"
  get "skins/:id/moderate", to: "skins#moderator_edit", as: "skin_moderate"
  get "skins/:id/upload-to-minecraft", to: "skins#minecraft_upload", as: "skin_minecraft_upload"
  post "skins/:id/favourite", to: "skins#add_favourite", as: "create_skin_favourite"
  post "skins/:id/upload-to-mineskin", to: "skins#mineskin_upload", as: "skin_mineskin_upload"
  patch "skins/:id/moderate", to: "skins#moderator_update", as: "update_skin_moderate"
  post "skins/:id/moderate/:action_id", to: "skins#quick_action", as: "skin_quick_action"
  patch "skins/:id/moderate/:action_id", to: "skins#quick_action"
  delete "skins/:id/favourite", to: "skins#remove_favourite", as: "destroy_skin_favourite"
  resources :skins, only: %i[create show edit destroy update]

  get "banners/random", to: "banners#random", as: "random_banner"
  post "banners/:id/favourite", to: "banners#add_favourite", as: "create_banner_favourite"
  delete "banners/:id/favourite", to: "banners#remove_favourite", as: "destroy_banner_favourite"

  scope :banner do
    get "/", to: "banners#new", as: "banner_editor"
  end

  scope :banners do
    get "/:id/moderate", to: "banners#moderator_edit", as: "banner_moderate"
    patch "/:id/moderate", to: "banners#moderator_update", as: "update_banner_moderate"
  end
  
  resources :banners, except: [:new, :index]

  constraints(title: /~[a-z0-9\-]*/) do
    get "banners/:id/:title", to: "banners#show", as: "banner_title"
    get "skins/:id/:title", to: "skins#show", as: "skin_title"
  end

  constraints(id: /@[a-z0-9_\-]+/) do
    get ":id", to: "users#show"
  end

  get "users", to: redirect("/")
  get "users/current", to: "users#current", as: "current_user"
  patch "profile", to: "users#update", as: "update_profile"

  get "modlog", to: "site#modlog", as: "modlog"
  get "preview", to: "site#preview", as: "preview"

  scope :webhooks do
    get "minecraftauth", to: "webhooks#minecraftauth", as: "minecraft_auth_webhook"
  end

  scope :terms do
    # get "/", to: "static#tos"
    get "/", to: redirect("/rules")
    get "mncs-archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
    get "mncs_archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
  end

  scope :guides do
    get "/", to: "guides#index", as: "guides"
    get "working-with-embeds", to: "guides#embeds", as: "embeds_guide"
    get "creating-your-first-skin", to: "guides#editor", as: "editor_guide"
  end

  get "badges", to: redirect("/hall-of-fame"), as: ""
  get "hall-of-fame", to: "badges#index", as: "badges"
  resources :badges, except: :index

  scope :users do
    get ":id", to: "users#redirect"
    resource :otp, controller: "otp", only: %i[update destroy] do
      get "backup-codes", to: "otp#backup_codes", as: "backup_codes"
      get "verify"
    end
    get ":id/moderate", to: "users#moderator_edit", as: "edit_profile_moderate"
    patch ":id/moderate", to: "users#moderator_update", as: "update_profile_moderate"
  end

  resources :users, only: %i[edit destroy update] do
    get "export", to: "users#export"
    
    get "accounts/connect", to: "minecraft_accounts#connect"
    post "accounts/:id/make_primary", to: "minecraft_accounts#make_primary", as: "make_account_primary"
    post "accounts/:id/change_skin", to: "minecraft_accounts#change_skin", as: "change_account_skin"
    post "accounts/:id/refresh", to: "minecraft_accounts#refresh", as: "refresh_account"
    resources :minecraft_accounts, only: %i[index destroy], path: "accounts", as: "accounts"
  end

  scope :editor do
    get "/", to: redirect("/")
  end

  # API
  scope :api do
    get "skin/:id", to: "api#skin"
    get "tags", to: "api#tags"
    get "outdated_browser", to: "api#outdated_browser_bypass"
  end

  # Mounts
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
end

app/models/banner.rb
class Banner < ApplicationRecord
  include PgSearch::Model
  include Favouriteable
  include GalleryFilters
  include Taggable
  include Searchable

  SortableByHot::KARMA_MULT = 0
  SortableByHot::FAVOURITES_MULT = 2.5
  include SortableByHot

  SURVIVAL_FRIENDLY_LENGTH = 14

  add_gallery_filters({
    tag: "tagged_with_cached",
    favourited_by: "favourited_by_user_name",
    search: "search",
    compatibility: "by_compatibility",
    style: "by_style",
  })

  attribute :terms_and_conditions, :boolean

  validates :name, :data, presence: true
  validates :data, uniqueness: true, format: {with: /\A[a-z]a([a-z]{2})+\z/i, message: "only allows valid banner codes"}
  validates :name, length: {maximum: 128}
  validates :description, length: {maximum: 1024}
  validates :terms_and_conditions, acceptance: true

  belongs_to :user
  has_many :modlogs, as: :target

  scope :hidden, -> { where(hidden: true) }
  scope :visible, -> { where.not(hidden: true) }
  scope :banner_compatible, -> { banner_style.or(any_style) }
  scope :shield_compatible, -> { shield_style.or(any_style) }
  scope :by_style, ->(style) {
    case style
    when "banner" then banner_compatible
    when "shield" then shield_compatible
    else all
    end
  }

  attribute :style, :integer, default: 0
  enum :style, %i[banner any shield], default: :banner, suffix: :style

  scope :survival_friendly, -> { where("LENGTH(data) <= ?", SURVIVAL_FRIENDLY_LENGTH) }
  scope :by_compatibility, ->(type) {
    case type
    when "survival" then survival_friendly
    when "command" then where.not(id: survival_friendly)
    end
  }

  def survival_friendly?
    data.size <= SURVIVAL_FRIENDLY_LENGTH
  end

  def tag_js
    tags.map { |tag| {value: tag.name} }.to_json
  end

  def can_user_edit?(some_user)
    some_user&.id == user_id
  end

  def to_url_title
    "~#{name.parameterize.tr("_", "-")}"
  end

  def to_title_path
    Routing.banner_title_path(self, to_url_title)
  end

  def to_title_url
    Routing.banner_title_url(self, to_url_title)
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update]
  before_action :set_banner, only: %i[show edit update moderator_edit moderator_update add_favourite remove_favourite]
  before_action :validate_can_edit, only: %i[edit update destroy]
  before_action :check_visibility, only: :show
  before_action :redirect_title, only: :show

  require_role :moderator, only: %i[moderator_edit moderator_update]
  nav_section :gallery
  nav_section :banner, only: :new
  layout "gallery", only: :index

  def index
    index_meta_config
    params[:page].to_i > 0 ? nil : params[:page] = 1
    items = (gallery_params[:items] || 24).to_i.clamp(1, 50)
    @gallery_params = gallery_params
    banners = Banner.visible.with_params(@gallery_params)
    banners = banners.merge(Banner.order_by_created) unless gallery_params[:order].present?

    if @gallery_params[:hidden] && current_user.authorized?(:moderator)
      banners = banners.merge(Banner.hidden)
    end
    
    @pagy, @banners = pagy(banners, items: items)
    @tags = @banners.top_tags

    @banners_all = banners
    @gallery_tab = :banners
  rescue Pagy::OverflowError
    not_found_error
  end

  def random
    banner = Banner.ordered_by("random").first
    if banner.present?
      redirect_to banner.to_title_path
    else
      not_found_error
    end
  end

  def new
    meta_config do |config|
      config.title = "Banner Maker"
      config.description = "Minecraft Banner Maker. Create Minecraft Banners for 1.21, and share with your friends."
    end

    @gallery_tab = :banners
    @banner = Banner.new
  end

  def show
    show_meta_config
    @gallery_tab = :banners
  end

  def create
    params = banner_params.dup
    params.delete(:tags)
    params[:tag_list] = transform_tags(banner_params[:tags])
    @banner = Banner.new(params)
    @banner.user = current_user

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner.to_title_path, notice: "Banner was successfully shared." }
      else
        format.html { redirect_to banner_editor_path, alert: "Error saving banner. #{format_errors @banner.errors.messages}" }
      end
    end
  end

  def update
    params = banner_params.dup
    params.delete(:tags)
    params[:tag_list] = transform_tags(banner_params[:tags])
    respond_to do |format|
      if @banner.update(params)
        format.html { redirect_to @banner.to_title_path, notice: "Banner was successfully updated." }
      else
        format.html { redirect_to edit_banner_path(@banner), alert: "Error saving banner." }
      end
    end
  end

  def destroy
  end

  def add_favourite
    respond_to do |format|
      if Favourite.add_favourite(current_user, @banner)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "favourite_banner_#{@banner.id}",
            partial: "banners/banner_favourite",
            locals: {banner: @banner, size: params[:size], redirect: params[:redirect]}
          )
        }
        format.html { redirect_to params[:redirect], notice: "Added banner to favourites." }
      else
        format.html { redirect_to params[:redirect], alert: "Error favouriting banner." }
      end
    end
  end

  def remove_favourite
    respond_to do |format|
      if Favourite.remove_favourite(current_user, @banner)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "favourite_banner_#{@banner.id}",
            partial: "banners/banner_favourite",
            locals: {banner: @banner, size: params[:size], redirect: params[:redirect]}
          )
        }
        format.html { redirect_to params[:redirect], notice: "Removed banner from favourites." }
      else
        format.html { redirect_to params[:redirect], alert: "Error removing favourite banner." }
      end
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to banners_gallery_path
  end

  def moderator_edit
  end

  def moderator_update
    old_attr = @banner.attributes
    old_attr["tag_list"] = @banner.tag_list
    reason = params[:reason]
    params = banner_params.dup
    params.delete(:tags)
    params[:tag_list] = transform_tags(banner_params[:tags])

    respond_to do |format|
      banner, modlog = nil
      ActiveRecord::Base.transaction do
        banner = @banner.update!(params)
        new_attr = @banner.reload.attributes
        new_attr["tag_list"] = @banner.tag_list
        modlog = Modlog.generate!(@banner, current_user, old_attr, new_attr, reason)
      end
      raise "Error saving banner or modlog" unless banner && modlog

      format.html { redirect_to @banner.to_title_path, notice: "Banner was successfully updated." }
    rescue
      format.html { redirect_to banner_moderate_path(@banner), alert: "Error saving banner." }
    end
  end

  private

  def gallery_params
    params.reject! { |_, value| !value.present? }
    params.slice(:user, :date_offset, :tag, :style, :favourited_by, :search, :order, :items, :compatibility, :hidden, :debug).permit!
  end

  def banner_params
    permit = [:name, :description, :style, :tags, :data, :terms_and_conditions]
    permit.append(:hidden) if current_user.authorized?(:moderator)
    params.require(:banner).permit(permit)
  end

  def set_banner
    @banner = Banner.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    not_found_error
  end

  def check_visibility
    return true unless @banner.hidden?
    if current_user.present?
      return true if @banner.user_id == current_user.id
      return true if current_user.authorized?(:moderator)
    end
    not_found_error
  end

  def redirect_title
    return unless request.format.html?
    return if @banner.to_url_title == params[:title]
    
    redirect_to @banner.to_title_path
  end

  def index_meta_config
    meta_config do |config|
      config.title = if params[:user].present?
        "Minecraft Banners by #{params[:user].titleize}"
      elsif params[:favourited_by].present?
        "#{params[:favourited_by].titleize}'s Favourite Banners"
      else
        "Minecraft Banners"
      end
      config.title << (params[:page].present? ? " (Page #{params[:page]})" : "")
      config.description = "Search and browse Minecraft banners created with our Banner Maker."
    end
  end

  def show_meta_config
    desc = if @banner.description.present?
      @banner.description.tr("\n", " ").delete_suffix(".").strip
    else
      "Banner by #{@banner.user.display_name}"
    end
    desc << ". A Minecraft banner, created with NeedCoolerShoes Banner Maker."

    meta_config do |config|
      config.title = "#{@banner.name.truncate(32)} by #{@banner.user.display_name.truncate(32)}"
      config.image_alt = "#{config.title} - Minecraft Banner"
      config.description = desc.truncate(130)
    end
  end

  def validate_can_edit
    return true if @banner.can_user_edit?(current_user)
    forbidden_error
  end
end

app/helpers/banners_helper.rb
module BannersHelper
  def banners_gallery_filter_tag(params, key, value, title = "", text = nil)
    selected = (params[key] == value)
    if selected
      link_to(text || value, banners_gallery_path(params.except(key)), title: title, class: "font-bold underline")
    else
      link_to(text || value, banners_gallery_path(params.merge({key => value})), title: title, class: "underline")
    end
  end

  def banners_gallery_tag_filter_tag(params, tag, title)
    tags = params[:tag].to_s.split(",").first(Taggable::TAG_STACK_LIMIT)
    classes = "underline"

    if tags.include?(tag)
      classes += " font-bold"
      tags.delete(tag)
    else
      tags.delete_at(-1) if tags.size > Taggable::TAG_STACK_LIMIT - 1
      tags << tag
    end

    return link_to(tag, banners_gallery_path(params.merge({tag: tags.join(",")})), title: title, class: classes) if tags.any?
    link_to(tag, banners_gallery_path(params.except(:tag)), title: title, class: classes)
  end
end

app/views/banners/_banner_favourite.html.erb
<%
  size ||= 24
  show_guests ||= false
  redirect ||= banners_gallery_path
%>
<%= turbo_frame_tag "favourite_" + dom_id(banner) do %>
  <% if current_user.present? %>
    <div>
      <% if banner.favourited_by?(current_user) %>
        <%= form_with url: destroy_banner_favourite_path(banner), method: :delete do |form| %>
          <div class="flex flex-col items-center">
            <%= form.button aria: { label: "Remove from Favourites" } do %>
              <%= heroicon "heart", variant: "solid", size: size, class: "text-red-500 hover:text-red-800", title: "Remove from Favourites" %>
            <% end %>
            <span class="leading-none text-xs text-gray-500">
              <%= simple_number banner.favourites_count if banner.favourites_count > 0 %>
            </span>
          </div>
          <%= form.hidden_field :redirect, value: redirect %>
          <%= form.hidden_field :size, value: size %>
        <% end %>
      <% else %>
        <%= form_with url: create_banner_favourite_path(banner) do |form| %>
          <div class="flex flex-col items-center">
            <%= form.button aria: { label: "Add to Favourites" } do %>
              <%= heroicon "heart", size: size, class: "text-red-500 hover:text-red-800", title: "Add to Favourites" %>
            <% end %>
            <span class="leading-none text-xs text-gray-500">
              <%= simple_number banner.favourites_count if banner.favourites_count > 0 %>
            </span>
          </div>
          <%= form.hidden_field :redirect, value: redirect %>
          <%= form.hidden_field :size, value: size %>
        <% end %>
      <% end %>
    </div>
  <% elsif show_guests %>
    <div class="flex flex-col items-center">
      <%= heroicon "heart", size: size, class: "text-gray-500", title: "Login to add to Favourites" %>
      <span class="leading-none text-xs text-gray-500">
        <%= simple_number banner.favourites_count if banner.favourites_count > 0 %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/banners/_form.html.erb
<h2 class="text-xl text-white">Upload Banner</h2>
<div class="flex justify-center" data-turbo="false">
  <div class="max-w-lg text-white">
    <%= form_for(banner, url: banners_path) do |form| %>
      <div class="flex flex-col gap-2">
        <div class="flex flex-col gap-2">
          <%= form.label :name, nil, class: "m-0" %>
          <%= form.text_field :name, autofocus: 1, class: "text-black" %>
        </div>

        <div class="flex flex-col gap-2">
          <%= form.label :description, "Description (Optional)", class: "m-0" %>
          <%= form.text_area :description, class: "text-black" %>
        </div>

        <div class="flex flex-col gap-2">
          <%= form.label :tags, nil, class: "m-0" %>
          <%= form.text_field :tags, value: "", data: { controller: "tagify", "tagify-for-value": "banner" } %>
        </div>

        <div>
          <%= form.check_box :terms_and_conditions, class: "w-4 h-4 inline-block" %>
          <%= form.label :terms_and_conditions, class: "m-0 inline text-sm" do %>
            I accept the terms and conditions as below.
          <% end %>
        </div>

        <%= form.hidden_field :data %>
        
        <div class="flex flex-col items-start" id="terms-and-conditions">
          <h2 class="text-white">Terms and Conditions</h2>
          <p class="text-xs mb-1">
            Submitting this banner, means that you agree to license it under the terms
            of the <%= link_to "CC BY-SA 4.0 License", "https://creativecommons.org/licenses/by-sa/4.0/", class: "text-white underline" %>.
          </p>
          <p class="text-xs mb-1">
            This allows for other users of the site to use your banner, or parts of it, to create their own.
          </p>
          <p class="text-xs">
            Submitting any banner to the site means you agree to abide by the
            <%= link_to "Site Rules", rules_path, class: "text-white underline"%>.
          </p>
        </div>

        <div class="mt-2 flex flex-col xs:flex-row gap-1 xs:gap-2">
          <%= form.submit "Upload Banner", class: "btn-ncs h-auto" %>
          <button id="share-cancel" class="btn-ncs" type="button">Cancel</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/banners/_form_fields.html.erb
<%
  styles = {
    "Only looks good as a Banner" => :banner,
    "Looks good as a Banner or Shield" => :any,
    "Only looks good as a Shield" => :shield,
  }
%>

<div class="flex flex-col gap-2">
  <%= form.label :name, nil, class: "m-0" %>
  <%= form.text_field :name, autofocus: 1, class: "text-black" %>
</div>

<div class="flex flex-col gap-2">
  <%= form.label :description, "Description (Optional)", class: "m-0" %>
  <div class="bg-white text-black">
    <%= form.marksmith :description, enable_file_uploads: false, rows: 4 %>
  </div>
</div>

<div class="flex flex-col gap-2">
  <%= form.label :description, "Banner Style", class: "m-0" %>
  <%= form.select :style, styles, {}, class: "text-black p-1" %>
  <% if banner.new_record? %>
    <p class="text-xs">
      You can use the toggle above the banner preview to see how the banner looks as a shield.
    </p>
  <% end %>
</div>

<div class="flex flex-col gap-2">
  <%= form.label :tags, nil, class: "m-0" %>
  <%= form.text_field :tags, value: banner.tag_js, data: { controller: "tagify", "tagify-for-value": "banner" } %>
</div>

app/views/banners/_form_moderator.erb
<div class="flex justify-center" data-turbo="false">
  <div class="max-w-lg text-white w-full">
    <%= form_for(banner, url: update_banner_moderate_path) do |form| %>
      <div class="flex flex-col gap-2">
        <%= render partial: "form_fields", locals: {form: form, banner: banner} %>

        <div class="flex flex-col gap-1">
          <%= label_tag :reason %>
          <%= text_field_tag :reason, "", class: "text-black", placeholder: "Reason for moderating this banner.", required: true %>
        </div>

        <div class="mt-2 flex flex-col xs:flex-row gap-1 xs:gap-2">
          <%= form.submit "Save", class: "btn-ncs h-auto" %>
          <%= link_to "Cancel", banner, class: "btn-ncs" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/banners/_form_moderator.html.erb
<div class="flex justify-center" data-turbo="false">
  <div class="max-w-lg text-white w-full">
    <%= form_for(banner, url: update_banner_moderate_path) do |form| %>
      <div class="flex flex-col gap-2">
        <%= render partial: "form_fields", locals: {form: form, banner: banner} %>

        <div>
          <div class="flex gap-1 items-center">
            <%= form.check_box :hidden %>
            <%= form.label :hidden, class: "select-none" %>
          </div>
          <span class="text-sm text-gray-400">
            Hidden banners do not show up in the gallery. Use only if the banner has violated the rules.
          </span>
        </div>

        <div class="flex flex-col gap-1">
          <%= label_tag :reason %>
          <%= text_field_tag :reason, "", class: "text-black", placeholder: "Reason for moderating this banner.", required: true %>
        </div>

        <div class="mt-2 flex flex-col xs:flex-row gap-1 xs:gap-2">
          <%= form.submit "Save", class: "btn-ncs h-auto" %>
          <%= link_to "Cancel", banner, class: "btn-ncs" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/banners/_new_form.html.erb
<div class="flex justify-center" data-turbo="false">
  <div class="max-w-lg text-white w-full">
    <%= form_for(banner, url: banners_path) do |form| %>
      <div class="flex flex-col gap-2">
        <%= render partial: "form_fields", locals: {form: form, banner: banner} %>

        <%= form.hidden_field :data %>

        <div>
          <%= form.check_box :terms_and_conditions, class: "w-4 h-4 inline-block" %>
          <%= form.label :terms_and_conditions, class: "m-0 inline text-sm" do %>
            I accept the terms and conditions as below.
          <% end %>
        </div>

        <div class="flex flex-col items-start" id="terms-and-conditions">
          <h2 class="text-white">Terms and Conditions</h2>
          <p class="text-xs mb-1">
            Submitting this banner, means that you agree to license it under the terms
            of the <%= link_to "CC BY-SA 4.0 License", "https://creativecommons.org/licenses/by-sa/4.0/", class: "text-white underline" %>.
          </p>
          <p class="text-xs mb-1">
            This allows for other users of the site to use your banner, or parts of it, to create their own.
          </p>
          <p class="text-xs">
            Submitting any banner to the site means you agree to abide by the
            <%= link_to "Site Rules", rules_path, class: "text-white underline"%>.
          </p>
        </div>

        <div class="mt-2 flex flex-col xs:flex-row gap-1 xs:gap-2">
          <%= form.submit banner.new_record? ? "Upload Banner" : "Update Banner", class: "btn-ncs h-auto" %>
          <button id="share-cancel" class="btn-ncs" type="button">Cancel</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/banners/_sign_in_form.html.erb
<h2 class="text-xl text-white">Sign In to Share to Gallery</h2>
<%= form_with(url: user_session_path, model: User) do |f| %>
  <div class="flex flex-col gap-2 w-full text-white">
    <div class="flex flex-col">
      <%= f.label :login %>
      <%= f.email_field :login, autofocus: true, autocomplete: "email", class: "text-black" %>
    </div>

    <div class="flex flex-col">
      <%= f.label :password %>
      <%= f.password_field :password, autocomplete: "current-password", class: "text-black" %>
    </div>

    <div class="flex justify-between">
      <%= f.label :remember_me, style: "flex-grow: 1; margin: 0px;" %>
      <%= f.check_box :remember_me, class: "!w-4 !h-4" %>
    </div>

    <div>
      <p>Don't have an account? <%= link_to "Sign up.", new_user_registration_path, class: "underline" %></p>
    </div>

    <div class="flex gap-2">
      <%= f.submit "Log in", class: "btn-ncs" %>
      <button id="share-cancel" class="btn-ncs" type="button">Cancel</button>
    </div>
  </div>
<% end %>

app/views/banners/edit.html.erb
<% content_for :styles do %>
  <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
<% end %>
<div class="flex justify-center w-full bg-ncs-tweed bg-ncs-gray-700 rounded text-white p-4">
  <div class="max-w-lg w-full">
    <h1 class="text-2xl">Edit Banner</h1>
    <%= render partial: "form", locals: { banner: @banner } %>
  </div>
</div>

app/views/banners/index.html.erb
<% content_for :filters do %>
  <%= render partial: "banners/index/banner_filters", locals: {params: @gallery_params, banners: @banners_all, tags: @tags} %>
<% end %>

<% content_for :before_gallery do %>
  <div class="md:hidden w-full pt-2">
    <%= render partial: "shared/search", locals: { classes: "w-full", btn_classes: "btn-ncs shrink w-auto" } %>
  </div>
<% end %>

<% content_for :styles do %>
  <%= stylesheet_link_tag "banner/components" %>
<% end %>
<% content_for :scripts do %>
  <script type="module">import "src/banner/components/banner";</script>
<% end %>

<%= render partial: "shared/pagy_nav", locals: { pagy: @pagy } %>
<div class="grow">
  <% if !@banners.any? %>
    <div class="flex flex-col gap-2 items-center">
      <h3 class="text-4xl font-bold text-white">NO BANNERS?</h3>
      <img src="<%= asset_path "megamewnd.png" %>" width="350" height="465.45" alt="Mascot">
      <p class="text-ncs-dark-300">Current search / filters yield no results.</p>
    </div>
  <% end %>
  <div class="grid grid-cols-1 mob:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    <%= render Gallery::BannerCardComponent.with_collection(@banners, params: @gallery_params) %>
  </div>
</div>
<%= render partial: "shared/pagy_nav", locals: { pagy: @pagy } %>

app/views/banners/moderator_edit.html.erb
<% content_for :styles do %>
  <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
<% end %>
<div class="flex justify-center w-full bg-ncs-tweed bg-ncs-gray-700 rounded text-white p-4">
  <div class="max-w-lg w-full">
    <h1 class="text-2xl">Moderate Banner</h1>
    <%= render partial: "form_moderator", locals: { banner: @banner } %>
  </div>
</div>