config/routes.rb
Rails.application.routes.draw do
  root "skins#new"

  devise_for :users, controllers: {sessions: "sessions"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "about", to: "static#about", as: "about"
  get "faq", to: "static#faq", as: "faq"
  get "contact", to: "static#contact", as: "contact"
  get "donate", to: "static#donate", as: "donate"
  post "contact", to: "static#send_message", as: "send_message"
  get "open-letter", to: "static#open_letter"
  get "open_letter", to: redirect("open-letter")
  get "rules", to: "static#rules"
  get "sitemap", to: "static#sitemap", defaults: {format: "xml"}

  # Gallery Routes
  get "gallery/banners", to: "banners#index", as: "banners_gallery"
  get "gallery/banners/:page", to: "banners#index"
  get "gallery/skins", to: "skins#index", as: "skins_gallery"
  get "gallery/skins/:page", to: "skins#index"
  get "gallery", to: redirect(path: "/gallery/skins")
  get "gallery/:page", to: redirect("/gallery/skins/%{page}")

  get "jam/:jam", to: redirect("/gallery/skins/?tag=%{jam}")

  get "skins", to: redirect("/gallery/skins")
  get "skins/random", to: "skins#random", as: "random_skin"
  get "skins/:id/download", to: "skins#download", as: "skin_download"
  get "skins/:id/texture", to: "skins#texture", as: "skin_texture"
  get "skins/:id/social", to: "skins#social", as: "skin_social"
  get "skins/:id/embed", to: "skins#embed", as: "skin_embed"
  get "skins/:id/moderate", to: "skins#moderator_edit", as: "skin_moderate"
  get "skins/:id/upload-to-minecraft", to: "skins#minecraft_upload", as: "skin_minecraft_upload"
  post "skins/:id/favourite", to: "skins#add_favourite", as: "create_skin_favourite"
  post "skins/:id/upload-to-mineskin", to: "skins#mineskin_upload", as: "skin_mineskin_upload"
  patch "skins/:id/moderate", to: "skins#moderator_update", as: "update_skin_moderate"
  post "skins/:id/moderate/:action_id", to: "skins#quick_action", as: "skin_quick_action"
  patch "skins/:id/moderate/:action_id", to: "skins#quick_action"
  delete "skins/:id/favourite", to: "skins#remove_favourite", as: "destroy_skin_favourite"
  resources :skins, only: %i[create show edit destroy update]

  get "banners/random", to: "banners#random", as: "random_banner"
  post "banners/:id/favourite", to: "banners#add_favourite", as: "create_banner_favourite"
  delete "banners/:id/favourite", to: "banners#remove_favourite", as: "destroy_banner_favourite"

  scope :banner do
    get "/", to: "banners#new", as: "banner_editor"
  end

  scope :banners do
    get "/:id/moderate", to: "banners#moderator_edit", as: "banner_moderate"
    patch "/:id/moderate", to: "banners#moderator_update", as: "update_banner_moderate"
  end
  
  resources :banners, except: [:new, :index]

  constraints(title: /~[a-z0-9\-]*/) do
    get "banners/:id/:title", to: "banners#show", as: "banner_title"
    get "skins/:id/:title", to: "skins#show", as: "skin_title"
  end

  constraints(id: /@[a-z0-9_\-]+/) do
    get ":id", to: "users#show"
  end

  get "users", to: redirect("/")
  get "users/current", to: "users#current", as: "current_user"
  patch "profile", to: "users#update", as: "update_profile"

  get "modlog", to: "site#modlog", as: "modlog"
  get "preview", to: "site#preview", as: "preview"

  scope :webhooks do
    get "minecraftauth", to: "webhooks#minecraftauth", as: "minecraft_auth_webhook"
  end

  scope :terms do
    # get "/", to: "static#tos"
    get "/", to: redirect("/rules")
    get "mncs-archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
    get "mncs_archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
  end

  scope :guides do
    get "/", to: "guides#index", as: "guides"
    get "working-with-embeds", to: "guides#embeds", as: "embeds_guide"
    get "creating-your-first-skin", to: "guides#editor", as: "editor_guide"
  end

  get "badges", to: redirect("/hall-of-fame"), as: ""
  get "hall-of-fame", to: "badges#index", as: "badges"
  resources :badges, except: :index

  scope :users do
    get ":id", to: "users#redirect"
    resource :otp, controller: "otp", only: %i[update destroy] do
      get "backup-codes", to: "otp#backup_codes", as: "backup_codes"
      get "verify"
    end
    get ":id/moderate", to: "users#moderator_edit", as: "edit_profile_moderate"
    patch ":id/moderate", to: "users#moderator_update", as: "update_profile_moderate"
  end

  resources :users, only: %i[edit destroy update] do
    get "export", to: "users#export"
    
    get "accounts/connect", to: "minecraft_accounts#connect"
    post "accounts/:id/make_primary", to: "minecraft_accounts#make_primary", as: "make_account_primary"
    post "accounts/:id/change_skin", to: "minecraft_accounts#change_skin", as: "change_account_skin"
    post "accounts/:id/refresh", to: "minecraft_accounts#refresh", as: "refresh_account"
    resources :minecraft_accounts, only: %i[index destroy], path: "accounts", as: "accounts"
  end

  scope :editor do
    get "/", to: redirect("/")
  end

  # API
  scope :api do
    get "skin/:id", to: "api#skin"
    get "tags", to: "api#tags"
    get "outdated_browser", to: "api#outdated_browser_bypass"
  end

  # Mounts
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
end

app/models/user.rb
class User < ApplicationRecord
  require "zip"

  include OtpAuthenticatable
  attr_writer :login

  YEAR_KARMA = 50
  FAVOURITE_RATIO = 0.02
  FAVOURITE_MAX = 25
  PIXEL_CACHE = 5.minutes
  ROLES = %i[moderator admin owner]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :trackable

  belongs_to :featured_skin, class_name: "Skin", foreign_key: "featured_skin_id", optional: true
  belongs_to :featured_badge, class_name: "Badge", foreign_key: "featured_badge_id", optional: true
  belongs_to :minecraft_account, optional: true

  has_many :skins, dependent: :destroy
  has_many :banners, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  has_many :favourites, dependent: :destroy
  has_many :skin_favourites, through: :skins, source: :favourites
  has_many :modlogs, as: :target, dependent: :destroy
  has_many :minecraft_accounts, dependent: :destroy

  validates :name,
    format: {with: /\A[a-z0-9\-_]+\z/, message: "only allows letters, numbers, dashes and underscores"},
    exclusion: {in: %w[sign_in sign_out password cancel sign_up edit current otp], message: "%{value} is reserved"},
    uniqueness: true,
    length: {maximum: 64}

  validates :email, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}, length: {maximum: 256}
  validates :attribution_message, length: {maximum: 64}, format: {with: /\A[ -~]+\z/}
  validates :biography, length: {maximum: 2048}

  scope :order_by_pixels, ->(order = :desc) { order(pixels: order) }
  scope :with_login, ->(login) { where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]) }

  enum :role, ROLES

  before_create :set_support_token, unless: :support_token?

  ROLES.each_with_index do |role, level|
    define_method :"#{role}?" do
      permission_level >= level
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).with_login(login.downcase).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def attribution_message
    read_attribute(:attribution_message) || name[..64]
  end

  def authorized?(role)
    return false unless User::ROLES.include?(role)
    level = User::ROLES.index(role)
    permission_level >= level
  end

  def permission_level
    return -1 unless role.is_a? String
    ROLES.find_index(role.to_sym)
  end

  def can_user_edit?(some_user)
    return false unless some_user.is_a? User
    return true if some_user.moderator?
    return true if some_user.id == id
    false
  end

  def display_name
    output = read_attribute("display_name")
    output = name unless output.present?
    output
  end

  def pixels!
    if PIXEL_CACHE > (Time.current - pixels_cached_at)
      return pixels
    end
    update_pixel_count!
  end

  def update_pixel_count!
    new_count = pixel_count
    update!(pixels: new_count, pixels_cached_at: Time.current)
    new_count
  end

  def featured_skin_data
    return featured_skin.data if featured_skin.present? && featured_skin.visible
    return skins.visible.last.data if skins.visible.any?
    ActionController::Base.helpers.asset_path("mncs_mascot_skin.png")
  end

  def banned?
    return false unless ban_ends_at.present?
    ban_ends_at > Time.current
  end

  def to_param
    name
  end

  def pixel_count
    count = badges.sum("badges.karma")
    count += skins.is_public.count * Skin::KARMA
    count += (Time.now.year - created_at.year) * YEAR_KARMA
    count += skin_favourites.where(target_id: Skin.is_public).sum("favourites.karma")
    count.clamp(0..)
  end

  def favourite_grant
    count = update_pixel_count!
    x = (count * FAVOURITE_RATIO)
    (Math.log(x + 1, 2) * 3).round
  end

  def export_skins_to_zip
    Skin.export_to_zip(skins)
  end

  def to_path
    "/@#{name}"
  end

  def to_url
    Routing.root_url + "@#{name}"
  end

  def login
    @login || self.name || self.email
  end

  def support_code
    totp = ROTP::TOTP.new(support_token, issuer: "NeedCoolerShoes")
    totp.at(Time.current.at_beginning_of_hour)
  end

  private

  def set_support_token
    self.support_token = ROTP::Base32.random
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update export]
  before_action :set_user, only: %i[show edit moderator_edit update moderator_update export]
  before_action :validates_current_user, only: %i[edit update export]

  require_role :moderator, only: %i[moderator_edit moderator_update]

  def redirect
    name = URI.encode_uri_component(params[:id].to_s)
    redirect_to("/@#{name}", status: :moved_permanently)
  end

  def show
    meta_config do |config|
      config.title = "#{@user.display_name}'s Profile".truncate(32)
      config.description = @user.biography&.tr("\n", " ")&.strip || "A Miner in Need of Cooler Shoes."
    end
  end

  def edit
    meta_config { |config| config.title = "Editing Profile".truncate(32) }
  end

  def moderator_edit
  end

  def current
    if current_user.present?
      redirect_to current_user.to_path
    else
      redirect_to root_path
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: "User updated successfully!" }
      else
        format.html { redirect_to user_path(@user), alert: "Error updating user!" }
      end
    end
  end

  def moderator_update
    old_attr = @user.attributes
    reason = params[:reason]
    respond_to do |format|
      user, modlog = nil
      ActiveRecord::Base.transaction do
        user = @user.update(user_params)
        new_attr = @user.reload.attributes
        modlog = Modlog.generate!(@user, current_user, old_attr, new_attr, reason)
      end
      raise "Error saving skin or modlog" unless skin && modlog

      format.html { redirect_to user_path(@user), notice: "User updated successfully!" }
    rescue
      format.html { redirect_to user_path(@user), alert: "Error updating user!" }
    end
  end

  def export
    send_file @user.export_skins_to_zip, filename: "#{@user.name}_#{Date.today.strftime "%Y%m%d"}.zip"
  end

  private

  def set_user
    name = (params[:user_id] || params[:id]).to_s.delete_prefix("@")

    @user = User.find_by!(name: name)
  rescue ActiveRecord::RecordNotFound
    not_found_error
  end

  def validates_current_user
    return true if @user.can_user_edit?(current_user)
    redirect_to root_path, alert: "You cannot edit another user."
  end

  def user_params
    params.except(:reason).require(:user).permit(:display_name, :biography, :featured_skin_id, :featured_badge_id, :password, :password_confirmation, :attribution_message, :watermark_disabled)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def authorized?(role, user = current_user)
    return false unless user.is_a? User
    user.authorized?(role)
  end

  def profile_link(user)
    link_to user.to_path do
      content = tag.span user.display_name, class: "underline"
      if (badge = user.featured_badge).present?
        content += " "
        content += tag.img src: badge.url, alt: badge.name, title: badge.name, class: "inline w-4 box-content"
      end
      if user.role?
        content += " "
        content += tag.img src: asset_path("medals/#{user.role}.png"), alt: user.role.titleize, title: user.role.titleize, class: "inline"
      end
      content
    end
  end
end

app/views/users/_actions_owner.html.erb
<!-- TODO -->
<div class="flex flex-col mob:flex-row mob:gap-2">
  <% if user.skins.any? %>
    <%= link_to "View My Uploads", skins_gallery_path(user: user.name), class: "btn-ncs" %>
  <% elsif user.banners.any? %>
    <%= link_to "View My Uploads", banners_gallery_path(user: user.name), class: "btn-ncs" %>
  <% end %>
  <% if user.favourites.any? %>
    <%= link_to "View My Favourites", skins_gallery_path(favourited_by: user.name), class: "btn-ncs" %>
  <% end %>
</div>
<div class="flex flex-col mob:flex-row mob:gap-2">
  <% if user.skins.any? %>
    <%= link_to "Export My Skins", user_export_path(user), class: "btn-ncs", "data-turbo": false %>
  <% end %>
  <%= link_to "Manage Accounts", user_accounts_path(user), class: "btn-ncs" %>
</div>
<div class="flex flex-col mob:flex-row mob:gap-2">
  <% if user == current_user %>
    <%= link_to "Edit Profile", edit_user_path(user), class: "btn-ncs" %>
    <%= link_to "Edit Login", edit_user_registration_path, class: "btn-ncs" %>
  <% else %>
    <%= link_to "Moderate User", edit_profile_moderate_path(user), class: "btn-ncs" %>
  <% end %>
</div>

app/views/users/_actions_visitor.html.erb
<!-- TODO -->
<% if user.skins.any? %>
  <%= link_to "View User's Uploads", skins_gallery_path(user: user.name), class: "btn-ncs" %>
<% elsif user.banners.any? %>
  <%= link_to "View User's Uploads", banners_gallery_path(user: user.name), class: "btn-ncs" %>
<% end %>
<% if user.favourites.any? %>
  <%= link_to "View User's Favourites", skins_gallery_path(favourited_by: user.name), class: "btn-ncs" %>
<% end %>

app/views/users/_form.html.erb
<!-- TODO -->
<%= form_with model: user do |form| %>
    <%= render partial: "form_fields", locals: { form: form, user: user } %>
    <div class="flex gap-2">
      <%= form.submit "Save", class: "btn-ncs" %>
      <%= link_to "Cancel", user, class: "btn-ncs" %>
    </div>
  </div>
<% end %>

app/views/users/_form_fields.html.erb
<!-- TODO -->
<%
  skins = user.skins.order_by_updated.pluck(:name, :id)
  badges = user.badges.pluck(:name, :id)
%>
<div class="flex flex-col gap-2">
  <div class="flex flex-col gap-1">
    <%= form.label :display_name %>
    <%= form.text_field :display_name, class: "text-black" %>
  </div>
  <p class="text-sm text-slate-300">
    If you wish to change your username, please <%= link_to "contact us", contact_path, class: "underline" %>.
  </p>

  <div class="flex flex-col gap-1">
    <%= form.label :biography, "Biography (Markdown Formatted)" %>
    <div class="bg-white text-black">
      <%= form.marksmith :biography, enable_file_uploads: false, rows: 6 %>
    </div>
  </div>

  <div class="flex flex-col gap-1">
    <%= form.label :attribution_message, "Attribution Message (Max 64, ASCII Characters)" %>
    <%= form.text_field :attribution_message, class: "text-black", maxlength: 64, pattern: '^[ -~]+$' %>
    <p class="text-sm text-slate-300">This will be used instead of your username inside skin watermarks.</p>
  </div>

  <div class="flex flex-col gap-1">
    <div class="flex items-center gap-1">
      <%= form.check_box :watermark_disabled %>
      <%= form.label :watermark_disabled, "Disable Skin Watermarking?" %>
    </div>
    <p class="text-sm text-slate-300">
      Disabling this will mean skins you upload will not be watermarked.
      They will not be able to be linked back to you if downloaded,
      then later uploaded again. This will not affect skins you have already uploaded.
    </p>
  </div>

  <div class="flex flex-col gap-1">
    <%= form.label :featured_skin_id %>
    <%= form.select :featured_skin_id, skins, {include_blank: "-- Always Show Latest --"}, class: "text-black capitalize p-1" %>
    <p class="text-sm text-slate-300">
      Chosen skin will be shown on your profile page. You can also change this from
      a skin's page.
    </p>
  </div>

  <% if user.badges.any? %>
    <div class="flex flex-col gap-1">
      <%= form.label :featured_badge_id %>
      <%= form.select :featured_badge_id, badges, {include_blank: "-- None --"}, class: "text-black capitalize p-1" %>
      <p class="text-sm text-slate-300">
        Chosen badge will be displayed next to your username.
      </p>
    </div>
  <% end %>

app/views/users/_form_moderator.html.erb
<!-- TODO -->
<%= form_with model: user, url: update_profile_moderate_path(user)  do |form| %>
  <%= render partial: "form_fields", locals: { form: form, user: user } %>

  <div class="flex flex-col gap-1">
    <%= label_tag :reason %>
    <%= text_field_tag :reason, "", class: "text-black" %>
  </div>

  <div class="flex gap-2">
    <%= form.submit "Save", class: "btn-ncs" %>
    <%= link_to "Cancel", user, class: "btn-ncs" %>
  </div>
<% end %>

app/views/users/_minecraft_account.html.erb
<%= minecraft_account.username %>

app/views/users/edit.html.erb
<!-- TODO -->
<div class="w-full bg-ncs-tweed bg-ncs-gray-700 rounded text-white overflow-clip">
  <div class="flex justify-center w-full p-4">
    <div class="w-full max-w-xl">
      <h1 class="text-2xl">Edit Profile</h1>
      <%= render partial: "form", locals: { user: @user } %>
    </div>
  </div>
</div>

app/views/users/linked_accounts.html.erb
<% content_for :title do %>
  <%= @user.display_name %>'s Linked Accounts
<% end %>

<div class="w-full bg-ncs-tweed bg-ncs-gray-700 rounded min-h-[600px]">
  <div class="text-white p-4">
    <div class="flex justify-between">
      <h2 class="text-2xl">Minecraft Accounts</h2>
      <div>
        <%= link_to "Add New", "", class: "btn-ncs px-2" %>
      </div>
    </div>
    <%= render partial: "minecraft_account", collection: @user.minecraft_accounts, as: :minecraft_account %>
  </div>
</div>

app/views/users/moderator_edit.html.erb
<!-- NOTHING TO TRANSLATE -->
<div class="w-full bg-ncs-tweed bg-ncs-gray-700 rounded text-white overflow-clip">
  <div class="flex justify-center w-full p-4">
    <div class="w-full max-w-xl">
      <h1 class="text-2xl">Moderate User</h1>
      <%= render partial: "form_moderator", locals: { user: @user } %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- TODO L37 L45 L49 -->
<% content_for :scripts do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>

<% content_for :styles do %>
  <%= stylesheet_link_tag "users" %>
<% end %>

<div class="w-full bg-ncs-tweed bg-ncs-gray-700 rounded text-white">
  <div class="flex flex-col tab:flex-row gap-4">
    <div class="flex flex-col bg-ncs-grid basis-2/5">
      <div
        class="flex items-center flex-wrap bg-ncs-gray-400 px-2 py-1
        bg-gradient-to-b from-ncs-gray-200"
      >
        <h1 class="text-2xl mr-2 line-clamp-1 break-all" title="<%= @user.display_name %>">
          <%= @user.display_name %>
          <% if @user.role? %>
            <img class="inline w-6" src="<%= asset_path("medals/#{@user.role}.png") %>" alt="<%= @user.role.titleize %>" title="<%= @user.role.titleize %>" style="image-rendering: pixelated;">
          <% end %>
        </h1>
        <span class="text-2xl text-gray-500">@<%= @user.name %></span>
      </div>
      <div class="relative h-full">
        <%= render partial: "skins/skin_3d", locals: { data: @user.featured_skin_data } %>
        <div class="absolute top-0 bottom-0 left-0 w-12 tab:hidden"></div>
        <div class="absolute top-0 bottom-0 right-0 w-12 tab:hidden"></div>
      </div>
      <script>
        window.addEventListener("load", () => {
          skinViewer.nameTag = "<%= @user.name %>";
        })
      </script>
    </div>
    <div class="flex flex-col gap-2 p-4 grow">
      <div class="bg-ncs-gray-300 rounded p-4 w-full">
        <h2 class="text-xl text-gray-500">Biography</h2>
        <div class="prose prose-invert">
          <% if @user.biography.present? %>
            <%= markdown @user.biography %>
          <% else %>
            <p>A Miner in Need of Cooler Shoes...</p>
          <% end %>
        </div>
      </div>
      <div class="bg-ncs-gray-300 rounded p-4 w-full">
        <h2 class="text-xl text-gray-500">Stats</h2>
        <table class="text-left">
          <tr>
            <th class="pr-4">Joined:</th>
            <td><%= simple_date @user.created_at %></td>
          </tr>
          <tr>
            <th class="pr-4">Public Skins:</th>
            <td><%= simple_number @user.skins.is_public.count %></td>
          </tr>
          <tr class="bg-rainbow-animated text-white/90">
            <th class="pr-4">Pixels:</th>
            <td><%= simple_number @user.pixels! %></td>
          </tr>
        </table>
        <% if current_user == @user || current_user&.moderator? %>
          <hr class="border-gray-500 my-2">
          <table class="text-left">
            <tr>
              <th class="pr-4">Support Code:</th>
              <td><%= @user.support_code.scan(/.{1,3}/).join("-") %></td>
            </tr>
          </table>
        <% end %>
      </div>
      <% if @user.badges.any? %>
        <div class="relative flex flex-wrap gap-2 bg-ncs-gray-300 rounded px-4 py-2 w-full">
          <% @user.user_badges.each do |user_badge| %>
            <% badge = user_badge.badge %>
            <div class="ncs-selectable cursor-pointer" tabindex="0">
              <img width="32" height="32" title="<%= badge.name %>" src="<%= badge.url %>" alt="<%= badge.name %>">
              <div class="cursor-auto overlay z-50 absolute flex flex-wrap gap-2 bg-ncs-gray-300 rounded px-4 py-2 mt-1 left-2 right-2 shadow border border-gray-600">
                <h2 class="font-bold"><%= badge.name %></h2>
                <p class="text-gray-400">Granted on <%= simple_date user_badge.created_at %></p>
                <p class="text-gray-200"><%= badge.description %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <div>
        <% if @user.can_user_edit?(current_user) %>
          <%= render partial: "actions_owner", locals: { user: @user } %>
        <% else %>
          <%= render partial: "actions_visitor", locals: { user: @user } %>
        <% end %>
      </div>
    </div>
  </div>
</div>