config/routes.rb
Rails.application.routes.draw do
  root "skins#new"

  devise_for :users, controllers: {sessions: "sessions"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "about", to: "static#about", as: "about"
  get "faq", to: "static#faq", as: "faq"
  get "contact", to: "static#contact", as: "contact"
  get "donate", to: "static#donate", as: "donate"
  post "contact", to: "static#send_message", as: "send_message"
  get "open-letter", to: "static#open_letter"
  get "open_letter", to: redirect("open-letter")
  get "rules", to: "static#rules"
  get "sitemap", to: "static#sitemap", defaults: {format: "xml"}

  # Gallery Routes
  get "gallery/banners", to: "banners#index", as: "banners_gallery"
  get "gallery/banners/:page", to: "banners#index"
  get "gallery/skins", to: "skins#index", as: "skins_gallery"
  get "gallery/skins/:page", to: "skins#index"
  get "gallery", to: redirect(path: "/gallery/skins")
  get "gallery/:page", to: redirect("/gallery/skins/%{page}")

  get "jam/:jam", to: redirect("/gallery/skins/?tag=%{jam}")

  get "skins", to: redirect("/gallery/skins")
  get "skins/random", to: "skins#random", as: "random_skin"
  get "skins/:id/download", to: "skins#download", as: "skin_download"
  get "skins/:id/texture", to: "skins#texture", as: "skin_texture"
  get "skins/:id/social", to: "skins#social", as: "skin_social"
  get "skins/:id/embed", to: "skins#embed", as: "skin_embed"
  get "skins/:id/moderate", to: "skins#moderator_edit", as: "skin_moderate"
  get "skins/:id/upload-to-minecraft", to: "skins#minecraft_upload", as: "skin_minecraft_upload"
  post "skins/:id/favourite", to: "skins#add_favourite", as: "create_skin_favourite"
  post "skins/:id/upload-to-mineskin", to: "skins#mineskin_upload", as: "skin_mineskin_upload"
  patch "skins/:id/moderate", to: "skins#moderator_update", as: "update_skin_moderate"
  post "skins/:id/moderate/:action_id", to: "skins#quick_action", as: "skin_quick_action"
  patch "skins/:id/moderate/:action_id", to: "skins#quick_action"
  delete "skins/:id/favourite", to: "skins#remove_favourite", as: "destroy_skin_favourite"
  resources :skins, only: %i[create show edit destroy update]

  get "banners/random", to: "banners#random", as: "random_banner"
  post "banners/:id/favourite", to: "banners#add_favourite", as: "create_banner_favourite"
  delete "banners/:id/favourite", to: "banners#remove_favourite", as: "destroy_banner_favourite"

  scope :banner do
    get "/", to: "banners#new", as: "banner_editor"
  end

  scope :banners do
    get "/:id/moderate", to: "banners#moderator_edit", as: "banner_moderate"
    patch "/:id/moderate", to: "banners#moderator_update", as: "update_banner_moderate"
  end
  
  resources :banners, except: [:new, :index]

  constraints(title: /~[a-z0-9\-]*/) do
    get "banners/:id/:title", to: "banners#show", as: "banner_title"
    get "skins/:id/:title", to: "skins#show", as: "skin_title"
  end

  constraints(id: /@[a-z0-9_\-]+/) do
    get ":id", to: "users#show"
  end

  get "users", to: redirect("/")
  get "users/current", to: "users#current", as: "current_user"
  patch "profile", to: "users#update", as: "update_profile"

  get "modlog", to: "site#modlog", as: "modlog"
  get "preview", to: "site#preview", as: "preview"

  scope :webhooks do
    get "minecraftauth", to: "webhooks#minecraftauth", as: "minecraft_auth_webhook"
  end

  scope :terms do
    # get "/", to: "static#tos"
    get "/", to: redirect("/rules")
    get "mncs-archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
    get "mncs_archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
  end

  scope :guides do
    get "/", to: "guides#index", as: "guides"
    get "working-with-embeds", to: "guides#embeds", as: "embeds_guide"
    get "creating-your-first-skin", to: "guides#editor", as: "editor_guide"
  end

  get "badges", to: redirect("/hall-of-fame"), as: ""
  get "hall-of-fame", to: "badges#index", as: "badges"
  resources :badges, except: :index

  scope :users do
    get ":id", to: "users#redirect"
    resource :otp, controller: "otp", only: %i[update destroy] do
      get "backup-codes", to: "otp#backup_codes", as: "backup_codes"
      get "verify"
    end
    get ":id/moderate", to: "users#moderator_edit", as: "edit_profile_moderate"
    patch ":id/moderate", to: "users#moderator_update", as: "update_profile_moderate"
  end

  resources :users, only: %i[edit destroy update] do
    get "export", to: "users#export"
    
    get "accounts/connect", to: "minecraft_accounts#connect"
    post "accounts/:id/make_primary", to: "minecraft_accounts#make_primary", as: "make_account_primary"
    post "accounts/:id/change_skin", to: "minecraft_accounts#change_skin", as: "change_account_skin"
    post "accounts/:id/refresh", to: "minecraft_accounts#refresh", as: "refresh_account"
    resources :minecraft_accounts, only: %i[index destroy], path: "accounts", as: "accounts"
  end

  scope :editor do
    get "/", to: redirect("/")
  end

  # API
  scope :api do
    get "skin/:id", to: "api#skin"
    get "tags", to: "api#tags"
    get "outdated_browser", to: "api#outdated_browser_bypass"
  end

  # Mounts
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
end

app/views/shared/_analytics.html.erb
<script defer="true" src="https://cdn.counter.dev/script.js" data-id="1c65258d-2dd0-44b5-8542-6aa28b3cec0b" data-utcoffset="10"></script>

app/views/shared/_favicons.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <div class="flex justify-center bg-yellow-400 p-2 relative z-50">
    <div class="max-w-ncs-content w-full">
      <p><%= notice %></p>
    </div>
  </div>
<% end %>

<% if alert.present? %>
  <div class="flex justify-center bg-red-500 p-2 relative z-50">
    <div class="max-w-ncs-content w-full">
      <p><%= alert %></p>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="flex flex-col items-center px-2 sm:px-4 pb-2 pt-1">
  <div class="flex flex-col gap-2 items-center sm:flex-row sm:justify-between text-sm max-w-ncs-content w-full">
    <div>
      <ul class="flex items-center flex-col sm:flex-row flex-wrap gap-1 sm:gap-2">
        <li><%= link_to "FAQ", faq_path, class: "text-black underline" %></li>
        <li><%= link_to "About", about_path, class: "text-black underline" %></li>
        <li><%= link_to "Contact", contact_path, class: "text-black underline" %></li>
        <li><%= link_to "Rules", rules_path, class: "text-black underline" %></li>
        <li><%= link_to "Donate", donate_path, class: "text-black underline" %></li>
        <li><%= link_to "Hall of Fame", badges_path, class: "text-black underline" %></li>
        <li><%= link_to "Moderation Log", modlog_path, class: "text-black underline" %></li>
        <li class="hidden sm:list-item">
          <span>|</span>
        </li>
        <li class="sm:hidden w-full py-2">
          <hr class="border-black w-full">
        </li>
        <li class="flex gap-2">
          <%= link_to "https://discord.gg/FEfbZYvQUa", target: "_blank", class: "text-black underline", title: "Join our Discord!" do %>
            <img src="<%= asset_path "social/discord.svg" %>" alt="Discord logo" class="w-4 h-4">
          <% end %>
          <%= link_to "https://github.com/NeedCoolerShoes/needcoolershoes", target: "_blank", class: "text-black underline", title: "Give us a star on Github!" do %>
            <img src="<%= asset_path "social/github.svg" %>" alt="Github logo" class="w-4 h-4">
          <% end %>
          <%= link_to "https://mastodon.social/@needcoolershoes", target: "_blank", class: "text-black underline", title: "Follow us on Mastodon!", rel: "me" do %>
            <img src="<%= asset_path "social/mastodon.svg" %>" alt="Mastodon logo" class="w-4 h-4">
          <% end %>
          <%= link_to "https://bsky.app/profile/needcoolershoes.com", target: "_blank", class: "text-black underline", title: "Follow us on Bluesky!" do %>
            <img src="<%= asset_path "social/bluesky.svg" %>" alt="Bluesky logo" class="w-4 h-4">
          <% end %>
          <%= link_to "https://www.youtube.com/@needcoolershoes", target: "_blank", class: "text-black underline", title: "Subscribe to our YouTube!" do %>
            <img src="<%= asset_path "social/youtube.svg" %>" alt="YouTube logo" class="w-4 h-4">
          <% end %>
        </li>
      </ul>
    </div>
    <div>
      <p class="text-center">
        <span>
          NeedCoolerShoes
          r:<a href="<%= Needcoolershoes::Config.revision_url %>" class="text-black underline font-monospace" title="NeedCoolerShoes revision">
            <%= Needcoolershoes::Config.revision %>
          </a>
        </span>
        by the
        <a href="/humans.txt" target="_blank" class="text-black underline">MNCS Restoration Team</a>
      </p>
    </div>
  </div>
</footer>

app/views/shared/_gallery_tabs.html.erb
<%
  selected ||= :skins
  tab_params = params.slice(:user, :favourited_by, :tag, :order, :date_offset, :debug).permit!
  tabs = [
    [:skins, "Skins", skins_gallery_path(tab_params)],
    [:banners, "Banners", banners_gallery_path(tab_params)],
  ]
%>

<ul class="flex items-end gap-1 text-lg mt-2 ncs-min:mt-4 font-bold">
  <% tabs.each do |tab| %>
    <%
      classes = (selected == tab[0] ? "bg-ncs-dark-800 text-ncs-dark-100 sm:py-1" : "bg-ncs-dark-700 text-ncs-dark-300 sm:py-0.5" )
    %>
    <li class="rounded-t-lg <%= classes %>"><%= link_to tab[1], tab[2], class: "px-4 sm:px-6" %></li>
  <% end %>
</ul>

app/views/shared/_head.html.erb
<%= render partial: "shared/meta" %>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>
<%= render partial: "shared/favicons" %>
<%= render partial: "shared/preloads" %>
<%= render partial: "shared/analytics" %>

app/views/shared/_header.html.erb
<% if Time.current.month == 6 %>
  <div id="pride" class="w-full h-[1px]"></div>
<% end %>
<%= yield :attention %>
<header class="sm:mx-16">
  <div class="flex items-center justify-center w-full">
    <div class="flex justify-between max-w-ncs-content w-full font-normal">
      <div class="grow navbar">
        <div class="flex justify-between px-3 sm:px-0">
          <a href="/" class="flex items-center gap-2 h-[47px] py-4" data-turbo="false">
            <img src="<%= asset_path "header.png" %>" alt="Site Logo" width="80" height="60"/>
            <p class="hidden sm:block uppercase text-sm text-white font-normal">Miners Need Cooler Shoes</p>
          </a>
          <div class="hidden lg:flex items-center justify-center">
            <%= render OpenCollectiveGoalComponent.new %>
          </div>
          <div class="flex items-center gap-2">
            <% if current_user.present? %>
              <% if current_user.authorized?(:admin) %>
                <%= link_to "Admin", "/admin", class: "text-white underline" %>
                <span class="text-white">|</span>
              <% end %>
              <%= link_to current_user.name, current_user.to_path, title: "#{current_user.pixels} pixels", class: "text-white underline" %>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "text-white btn-none underline" %>
            <% else %>
              <%= link_to "Create an Account", new_user_registration_path, class: "text-white underline" %>
              <%= link_to "Sign In", new_user_session_path, class: "text-white underline" %>
            <% end %>
          </div>
        </div>

        <div class="h-[64px] bg-[#edce14] relative z-50 overflow-x-clip sm:overflow-x-visible">
          <div class="flex items-center justify-between gap-2 relative z-50 bg-ncs-flourish bg-repeat-x h-full px-3 sm:px-0">
            <%= render partial: "shared/header_nav" %>
            <div class="hidden md:block">
              <%= render partial: "shared/search", locals: { classes: "max-w-[12rem] lg:max-w-none" } %>
            </div>
          </div>

          <div class="absolute w-[64px] h-[80px] top-0 left-[-52px] sm:left-[-64px] bg-ncs-flourish-side"></div>
          <div class="absolute w-[64px] h-[80px] top-0 right-[-52px] sm:right-[-64px] bg-ncs-flourish-side -scale-x-100"></div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_nav.html.erb
<%
  gallery = (@gallery_tab == :banners ? banners_gallery_path : skins_gallery_path)
  links = [
    [:editor, "Editor", root_path],
    [:banner, "Banner", banner_editor_path],
    [:gallery, "Gallery", gallery],
  ]
%>

<nav class="flex items-center gap-2 sm:gap-4 h-full uppercase" data-turbo="false">
  <% links.each_with_index do |item, idx| %>
    <span class="font-normal text-lg sm:text-2xl">
      <a class="<%= class_on_nav(item[0], "font-bold text-ncs-header-selected", "text-ncs-header-base hover:text-ncs-header-hover duration-300 transition-colors") %>" href="<%= item[2] %>">
        <%= item[1] %>
      </a>
    </span>
    <% if idx != (links.size - 1) %>
      <span class="text-sm sm:text-base text-ncs-header-base">●</span>
    <% end %>
  <% end %>
</nav>

app/views/shared/_meta.html.erb
<title>
  <%= meta_config.title %><%= meta_config.site_title %>
</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="<%= meta_config.description %>">
<meta property="og:site_name" content="NeedCoolerShoes">
<meta property="og:type" content="website">
<meta property="twitter:card" content="summary_large_image">
<meta property="og:title" content="<%= meta_config.title %><%= meta_config.site_title %>">
<meta property="og:image" content="<%= meta_config.image %>">
<meta property="twitter:title" content="<%= meta_config.title %>">
<meta property="twitter:image" content="<%= meta_config.image_alt %>">
<meta property="og:image:alt" content="<%= meta_config.image_alt %>">
<meta property="twitter:image:alt" content="<%= meta_config.image_alt %>">
<meta name="og:description" content="<%= meta_config.description %>">
<meta name="twitter:description" content="<%= meta_config.description %>">

<%= tag(:link, href: canonical_href, rel: :canonical) %>
<link type="text/plain" rel="author" href="/humans.txt" />

app/views/shared/_pagy_nav.html.erb
<div class="flex justify-start">
  <%== pagy_nav(pagy, size: [1,2,2,1]) %>
</div>

app/views/shared/_preloads.html.erb
<link rel="preload" as="image" href="<%= asset_path "flourish.png" %>" />
<link rel="preload" as="image" href="<%= asset_path "flourish-side.png" %>" />

app/views/shared/_search.html.erb
<%
  classes ||= ""
  btn_classes ||= ""
  gallery_path = (@gallery_tab == :banners ? banners_gallery_path : skins_gallery_path)
  search_type = (@gallery_tab == :banners ? "banners" : "skins")
%>
<%= form_with url: gallery_path, method: :get do |form| %>
  <div class="flex gap-2 w-full">
    <%= form.text_field :search, value: params[:search], "aria-label": "Search for #{search_type}", placeholder: "Search for #{search_type}", class: "bg-ncs-dark-800 text-ncs-dark-100 md:text-black md:bg-ncs-yellow-200 h-8 #{classes}" %>
    <%= form.button name: "", class: "cursor-pointer btn-none #{btn_classes}", aria: {label: "Search"} do %>
      <%= heroicon "magnifying-glass", size: 25 %>
    <% end %>
  </div>
<% end %>

app/views/shared/_welcome.html.erb
<% content_for :attention do %>
  <div class="flex justify-center w-full p-2 bg-ncs-yellow-200">
    <p>
      Welcome to Miners Need Cooler Shoes! This site is a continuation of the work done on
      <%= link_to "coolshoes.moxvallix.com", "https://coolshoes.moxvallix.com", class: "underline" %>,
      but with plenty more features!
    </p>
  </div>
<% end %>