config/routes.rb
Rails.application.routes.draw do
  root "skins#new"

  devise_for :users, controllers: {sessions: "sessions"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "about", to: "static#about", as: "about"
  get "faq", to: "static#faq", as: "faq"
  get "contact", to: "static#contact", as: "contact"
  get "donate", to: "static#donate", as: "donate"
  post "contact", to: "static#send_message", as: "send_message"
  get "open-letter", to: "static#open_letter"
  get "open_letter", to: redirect("open-letter")
  get "rules", to: "static#rules"
  get "sitemap", to: "static#sitemap", defaults: {format: "xml"}

  # Gallery Routes
  get "gallery/banners", to: "banners#index", as: "banners_gallery"
  get "gallery/banners/:page", to: "banners#index"
  get "gallery/skins", to: "skins#index", as: "skins_gallery"
  get "gallery/skins/:page", to: "skins#index"
  get "gallery", to: redirect(path: "/gallery/skins")
  get "gallery/:page", to: redirect("/gallery/skins/%{page}")

  get "jam/:jam", to: redirect("/gallery/skins/?tag=%{jam}")

  get "skins", to: redirect("/gallery/skins")
  get "skins/random", to: "skins#random", as: "random_skin"
  get "skins/:id/download", to: "skins#download", as: "skin_download"
  get "skins/:id/texture", to: "skins#texture", as: "skin_texture"
  get "skins/:id/social", to: "skins#social", as: "skin_social"
  get "skins/:id/embed", to: "skins#embed", as: "skin_embed"
  get "skins/:id/moderate", to: "skins#moderator_edit", as: "skin_moderate"
  get "skins/:id/upload-to-minecraft", to: "skins#minecraft_upload", as: "skin_minecraft_upload"
  post "skins/:id/favourite", to: "skins#add_favourite", as: "create_skin_favourite"
  post "skins/:id/upload-to-mineskin", to: "skins#mineskin_upload", as: "skin_mineskin_upload"
  patch "skins/:id/moderate", to: "skins#moderator_update", as: "update_skin_moderate"
  post "skins/:id/moderate/:action_id", to: "skins#quick_action", as: "skin_quick_action"
  patch "skins/:id/moderate/:action_id", to: "skins#quick_action"
  delete "skins/:id/favourite", to: "skins#remove_favourite", as: "destroy_skin_favourite"
  resources :skins, only: %i[create show edit destroy update]

  get "banners/random", to: "banners#random", as: "random_banner"
  post "banners/:id/favourite", to: "banners#add_favourite", as: "create_banner_favourite"
  delete "banners/:id/favourite", to: "banners#remove_favourite", as: "destroy_banner_favourite"

  scope :banner do
    get "/", to: "banners#new", as: "banner_editor"
  end

  scope :banners do
    get "/:id/moderate", to: "banners#moderator_edit", as: "banner_moderate"
    patch "/:id/moderate", to: "banners#moderator_update", as: "update_banner_moderate"
  end
  
  resources :banners, except: [:new, :index]

  constraints(title: /~[a-z0-9\-]*/) do
    get "banners/:id/:title", to: "banners#show", as: "banner_title"
    get "skins/:id/:title", to: "skins#show", as: "skin_title"
  end

  constraints(id: /@[a-z0-9_\-]+/) do
    get ":id", to: "users#show"
  end

  get "users", to: redirect("/")
  get "users/current", to: "users#current", as: "current_user"
  patch "profile", to: "users#update", as: "update_profile"

  get "modlog", to: "site#modlog", as: "modlog"
  get "preview", to: "site#preview", as: "preview"

  scope :webhooks do
    get "minecraftauth", to: "webhooks#minecraftauth", as: "minecraft_auth_webhook"
  end

  scope :terms do
    # get "/", to: "static#tos"
    get "/", to: redirect("/rules")
    get "mncs-archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
    get "mncs_archive", to: redirect("https://web.archive.org/web/20221128185339/https://www.needcoolshoes.com/terms")
  end

  scope :guides do
    get "/", to: "guides#index", as: "guides"
    get "working-with-embeds", to: "guides#embeds", as: "embeds_guide"
    get "creating-your-first-skin", to: "guides#editor", as: "editor_guide"
  end

  get "badges", to: redirect("/hall-of-fame"), as: ""
  get "hall-of-fame", to: "badges#index", as: "badges"
  resources :badges, except: :index

  scope :users do
    get ":id", to: "users#redirect"
    resource :otp, controller: "otp", only: %i[update destroy] do
      get "backup-codes", to: "otp#backup_codes", as: "backup_codes"
      get "verify"
    end
    get ":id/moderate", to: "users#moderator_edit", as: "edit_profile_moderate"
    patch ":id/moderate", to: "users#moderator_update", as: "update_profile_moderate"
  end

  resources :users, only: %i[edit destroy update] do
    get "export", to: "users#export"
    
    get "accounts/connect", to: "minecraft_accounts#connect"
    post "accounts/:id/make_primary", to: "minecraft_accounts#make_primary", as: "make_account_primary"
    post "accounts/:id/change_skin", to: "minecraft_accounts#change_skin", as: "change_account_skin"
    post "accounts/:id/refresh", to: "minecraft_accounts#refresh", as: "refresh_account"
    resources :minecraft_accounts, only: %i[index destroy], path: "accounts", as: "accounts"
  end

  scope :editor do
    get "/", to: redirect("/")
  end

  # API
  scope :api do
    get "skin/:id", to: "api#skin"
    get "tags", to: "api#tags"
    get "outdated_browser", to: "api#outdated_browser_bypass"
  end

  # Mounts
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"
end

app/controllers/skins_controller.rb
class SkinsController < ApplicationController
  before_action :authenticate_user!, only: %i[create update edit destroy minecraft_upload mineskin_upload]
  before_action :set_skin, only: %i[
    show edit moderator_edit update moderator_update download minecraft_upload
    texture destroy add_favourite remove_favourite preview social embed mineskin_upload quick_action
  ]
  before_action :validate_can_edit, only: %i[edit update destroy]
  before_action :check_visibility, only: %i[show download social embed]
  before_action :check_ban, only: %i[create]
  before_action :redirect_title, only: :show

  require_role :moderator, only: %i[moderator_edit moderator_update quick_action]
  
  nav_section :gallery
  nav_section :editor, only: :new

  after_action :allow_iframe, only: :embed

  layout "gallery", only: :index

  def index
    @gallery_params = gallery_params
    set_jam_info
    skins = Skin.with_params(@gallery_params)
    skins = skins.merge(Skin.order_by_created) unless gallery_params[:order].present?
    skins = if current_user.present?
      if @gallery_params[:hidden] && current_user.authorized?(:moderator)
        skins.merge(Skin.hidden)
      else
        skins.merge(Skin.visible_to_user(current_user))
      end
    else
      skins.merge(Skin.visible.is_public)
    end
    params[:page].to_i > 0 ? nil : params[:page] = 1
    items = (gallery_params[:items] || 24).to_i.clamp(1, 50)
    @pagy, @skins = pagy(skins, items: items)
    @tags = @skins.top_tags(10)

    index_meta_config
  rescue Pagy::OverflowError
    not_found_error
  end

  def show
    show_meta_config
    @attributions = @skin.attributions.attributed_visible_to_user(current_user).with_attributed_skin
    @variants = @skin.variants.visible_to_user(current_user)
    respond_to do |format|
      format.png { send_data @skin.preview_img, type: "image/png", disposition: "inline" }
      format.html { render }
      format.any { render }
    end
  end

  def social
    respond_to do |format|
      format.png { send_data @skin.social_img, type: "image/png", disposition: "inline" }
    end
  end

  def new
    @message = SiteMessage.latest&.message
  end

  def create
    params = skin_params.dup
    params.delete(:tags)
    params[:tag_list] = transform_tags(skin_params[:tags])
    @skin = Skin.new(params.except(:attributions))
    @skin.user = current_user

    license = :cc_by_sa_4
    license = :mncs if @skin.created_by_archive?
    license = :arr if @skin.created_by_arr?
    @skin.license = license

    respond_to do |format|
      if @skin.save
        if params[:attributions].is_a? Array
          params[:attributions].each { |url| SkinAttribution.create_from_url(@skin, *url.split(/\r\n|\r|\n/)) }
        end
        format.html { redirect_to @skin.to_title_path, notice: "Skin was successfully created." }
      else
        format.html { redirect_to root_path, alert: "Error saving skin. #{format_errors @skin.errors.messages}" }
      end
    end
  end

  def edit
    meta_config { |config| config.title = "Editing Skin" }
  end

  def update
    params = skin_params.dup
    params.delete(:tags)
    params[:tag_list] = transform_tags(skin_params[:tags])
    respond_to do |format|
      if @skin.update(params)
        format.html { redirect_to @skin.to_title_path, notice: "Skin was successfully updated." }
      else
        format.html { redirect_to edit_skin_path(@skin), alert: "Error saving skin. #{format_errors @skin.errors.messages}" }
      end
    end
  end

  def embed
    respond_to do |format|
      format.html { render layout: false }
      format.any { not_found_error }
    end
  end

  def moderator_edit
    meta_config { |config| config.title = "Moderating Skin" }
  end

  def moderator_update
    old_attr = @skin.attributes
    old_attr["tag_list"] = @skin.tag_list
    reason = params[:reason]
    params = skin_params.dup
    params.delete(:tags)
    params[:tag_list] = transform_tags(skin_params[:tags])

    respond_to do |format|
      skin, modlog = nil
      ActiveRecord::Base.transaction do
        skin = @skin.update!(params)
        new_attr = @skin.reload.attributes
        new_attr["tag_list"] = @skin.tag_list
        modlog = Modlog.generate!(@skin, current_user, old_attr, new_attr, reason)
      end
      raise "Error saving skin or modlog" unless skin && modlog

      format.html { redirect_to @skin.to_title_path, notice: "Skin was successfully updated." }
    rescue
      format.html { redirect_to skin_moderate_path(@skin), alert: "Error saving skin." }
    end
  end

  def download
    send_data @skin.to_png, type: "image/png", filename: "download.png"
    unless current_user == @skin.user
      @skin.download_count = (@skin.download_count || 0) + 1
      @skin.save(touch: false)
    end
  end

  def texture
    respond_to do |format|
      format.png { send_data @skin.to_png, type: "image/png", disposition: "inline" }
    end
  end

  def destroy
    @skin.destroy
    respond_to do |format|
      format.html { redirect_to skins_gallery_path, notice: "Skin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_favourite
    respond_to do |format|
      if Favourite.add_favourite(current_user, @skin)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "favourite_skin_#{@skin.id}",
            partial: "skins/skin_favourite",
            locals: {skin: @skin, size: params[:size], redirect: params[:redirect]}
          )
        }
        format.html { redirect_to params[:redirect], notice: "Added skin to favourites." }
      else
        format.html { redirect_to params[:redirect], alert: "Error favouriting skin." }
      end
    end
  end

  def remove_favourite
    respond_to do |format|
      if Favourite.remove_favourite(current_user, @skin)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "favourite_skin_#{@skin.id}",
            partial: "skins/skin_favourite",
            locals: {skin: @skin, size: params[:size], redirect: params[:redirect]}
          )
        }
        format.html { redirect_to params[:redirect], notice: "Removed skin from favourites." }
      else
        format.html { redirect_to params[:redirect], alert: "Error removing favourite skin." }
      end
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to skins_gallery_path
  end

  def random
    skin = Skin.visible_to_user(current_user).ordered_by("random").first
    redirect_to skin.to_title_path
  end

  def preview
  end

  def minecraft_upload
    @minecraft_accounts = current_user.minecraft_accounts.authenticated.order_by_primary
  end

  def mineskin_upload
    return forbidden_error if !current_user.moderator? && !@skin.skin_part.can_manually_upload?
    return forbidden_error if @skin.minecraft_texture_url?

    @skin.schedule_mineskin_upload

    respond_to do |format|
      format.html { redirect_to @skin, notice: "Skin is being uploaded..." }
    end
  end

  def quick_action
    redirect_path = params[:redirect] || skins_gallery_path

    respond_to do |format|
      case params[:action_id]
      when "duplicate" then qa_moderate(format, redirect_path, {visibility: :is_unlisted}, "Skin is a duplicate of another skin.")
      when "slim" then qa_moderate(format, redirect_path, {model: :slim}, "Changed skin model from Classic to Slim.")
      when "nsfw" then qa_moderate(format, redirect_path, {hidden: true}, "NSFW content is not allowed on the site.")
      when "hate" then qa_moderate(format, redirect_path, {hidden: true}, "Imagery of Nazis / hate groups is not allowed on the site.")
      when "categorize" then qa_moderate(format, redirect_path, skin_params, "Moved skin to another part / category.")
      else not_found_error
      end
    end
  end

  private

  def index_meta_config
    meta_config do |config|
      if params[:user].present?
        config.title = "Minecraft Skins by #{params[:user].titleize}"
        config.description = "Browse minecraft skins created by #{params[:user].titleize}."
      elsif params[:favourited_by].present?
        config.title = "#{params[:favourited_by].titleize}'s Favorite Skins"
        config.description = "Browse minecraft skins favorited by #{params[:favourited_by].titleize}."
      else
        config.title = "Minecraft Skins"
        config.description = "Browse minecraft skins created with our skin editor, by part, category or tag."
      end
      config.title << (@pagy.page > 1 ? " (Page #{@pagy.page})" : "")

      if @jam.present?
        config.title = @jam.name
        config.description = @jam.description.to_s.split("\n")&.first&.strip || "Minecraft skin jam."
      end
    end
  end

  def show_meta_config
    desc = if @skin.description.present?
      @skin.description.tr("\n", " ").delete_suffix(".").strip
    else
      "Skin by #{@skin.user.display_name}"
    end
    desc << ". A Minecraft skin, created with NeedCoolerShoes Skin Editor."

    meta_config do |config|
      config.title = "#{@skin.name.to_s.truncate(32)} by #{@skin.user.display_name.truncate(32)}"
      config.image = skin_social_url(@skin, format: :png)
      config.image_alt = "#{config.title} - Minecraft Skin"
      config.description = desc.to_s.truncate(130)
    end
  end

  def render_img_missing
    img = File.read("app/assets/images/missing_img.png")

    respond_to do |format|
      format.png { send_data img, type: "image/png", disposition: "inline", status: 200 }
      format.json { render json: {error: 404, message: "Skin not found."}, status: 404 }
      format.any { not_found_error }
    end
  end

  def set_skin
    @skin = Skin.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_img_missing
  end

  def redirect_title
    return unless request.format.html?
    return if @skin.to_url_title == params[:title]

    redirect_to @skin.to_title_path
  end

  def set_jam_info
    return unless params[:tag].present?

app/helpers/skins_helper.rb
module SkinsHelper
  def pagy_url_for(pagy, page, absolute: false, html_escaped: false) # it was (page, pagy) in previous versions
    params = request.query_parameters.merge(pagy.vars[:page_param] => page, :only_path => !absolute)
    html_escaped ? url_for(params).gsub("&", "&amp;") : url_for(params)
  end

  def skins_gallery_filter_tag(params, key, value, title = "", text = nil)
    selected = (params[key] == value)
    if selected
      link_to(text || value, skins_gallery_path(params.except(key)), title: title, class: "font-bold underline")
    else
      link_to(text || value, skins_gallery_path(params.merge({key => value})), title: title, class: "underline")
    end
  end

  def skins_gallery_tag_filter_tag(params, tag, title)
    tags = params[:tag].to_s.split(",").first(Taggable::TAG_STACK_LIMIT)
    classes = "underline"

    if tags.include?(tag)
      classes += " font-bold"
      tags.delete(tag)
    else
      tags.delete_at(-1) if tags.size > Taggable::TAG_STACK_LIMIT - 1
      tags << tag
    end

    return link_to(tag, skins_gallery_path(params.merge({tag: tags.join(",")})), title: title, class: classes) if tags.any?
    link_to(tag, skins_gallery_path(params.except(:tag)), title: title, class: classes)
  end
end

app/views/skins/_tag_link.html.erb
<!-- NOTHING TO TRANSLATE -->
<%= 
  link_to tag.name,
  skins_gallery_path(params.merge(tag: tag.name)),
  title: "#{tag.name} - #{tag.taggings_count}",
  onclick: "event.stopImmediatePropagation()"
%> 

app/views/skins/edit.html.erb
<!-- TRANSLATED -->

<% content_for :scripts do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>
<% content_for :styles do %>
  <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
<% end %>
<div class="w-full bg-ncs-tweed bg-ncs-gray-700 rounded text-white overflow-clip">
  <div class="flex flex-col items-center md:flex-row gap-2 w-full p-4">
    <div class="max-w-[320px] w-full h-[700px]">
      <%= render partial: "skin_3d", locals: { data: @skin.data, width: 300, height: 400 } %>
    </div>
    <script>
      skinViewer.nameTag = "<%= current_user.name %>"
    </script>
    <div class="w-full max-w-xl">
      <h1 class="text-2xl">Edit Skin</h1>
      <%= render partial: "form", locals: { skin: @skin } %>
      <%= form_with url: skin_path(@skin), method: :delete, class: "w-full" do |form| %>
        <%= form.submit t("skins.delete"), class: "underline text-white cursor-pointer mt-8 float-right", data: { "turbo-confirm": t("skins.delete_confirmation") } %>
      <% end %>
    </div>
  </div>
</div>

app/views/skins/show.html.erb
<!-- TRANSLATED -->

<% content_for :scripts do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>

<% content_for :styles do %>
  <%= stylesheet_link_tag "skins" %>
<% end %>

<%= turbo_stream_from @skin, :give_command %>

<div class="flex flex-col sm:flex-row items-center sm:items-start gap-2">
  <div class="sm:max-w-[250px] lg:max-w-[364px] w-full">
    <div class="col-left flex flex-col gap-2">
      <div class="relative checker-border bg-ncs-grid">
        <div class="h-[320px] sm:h-[400px]">
          <%= render partial: "skin_3d", locals: { data: @skin.data, model: @skin.skinview_model } %>
        </div>
        <% if current_user.present? %>
          <script>
            skinViewer.nameTag = "<%= current_user.name %>"
          </script>
        <% end %>
        <div class="absolute top-0 bottom-0 left-0 w-12 sm:hidden"></div>
        <div class="absolute top-0 bottom-0 right-0 w-12 sm:hidden"></div>
      </div>
      <div
        class="model hidden" data-user-id="<%= @skin.user_id %>" data-id="<%= @skin.id %>"
        data-local="<%= @skin.data %>" data-save="<%= @skin.data %>"
      ></div>
      <div>
        <% if @skin.user == current_user && @skin.user.featured_skin != @skin %>
          <%= form_with model: current_user, url: user_path(current_user) do |form| %>
            <%= form.hidden_field :featured_skin_id, value: @skin.id %>
            <%= form.submit t("skins.feature"), class: "btn-ncs", title: t("skins.feature_tooltip") %>
          <% end %>
        <% end %>
        <% if @skin.can_user_edit?(current_user) %>
          <% if @skin.user == current_user %>
            <%= link_to t("common.edit"), edit_skin_path(@skin), class: "btn-ncs" %>
          <% else %>
            <%= link_to t("common.moderate"), skin_moderate_path(@skin), class: "btn-ncs" %>
          <% end %>
        <% end %>
      </div>
      <div class="flex flex-col gap-1">
        <button
          onclick="editSkin('<%= @skin.data %>', '<%= @skin.attribution_string(true) %>', '<%= @skin.model %>')"
          class="edit btn-ncs mb-0.5" <%= @skin.can_user_open_in_editor?(current_user) ? nil : "disabled" %>
        >
          <%= t("common.editor") %>
        </button>
        <%= link_to t("skins.change_skin"), skin_minecraft_upload_path(@skin), class: "btn-ncs mb-0.5", data: { turbo: false } %>
        <%= link_to t("skins.download"), skin_download_path(@skin), class: "btn-ncs", data: { turbo: false } %>
      </div>
    </div>
  </div>
  <div class="w-full flex flex-col gap-2">
    <div class="bg-ncs-dark-700 p-4 text-ncs-dark-100">
      <div class="flex justify-between">
        <h2 class="text-4xl font-bold max-w-lg line-clamp-2" style="overflow-wrap: break-word;" title="<%= @skin.name %>"><%= @skin.name %></h2>
        <div>
          <%= render partial: "skin_favourite", locals: { skin: @skin, size: 32, redirect: skin_path(@skin) } %>
        </div>
      </div>
      <div class="flex flex-col font-bold">
        <p class="text-ncs-dark-300"><%= @skin.skin_part.name %> - <%= @skin.skin_category.name %></p>
        <p>
          by <%= profile_link @skin.user %>
        </p>
        <% if @skin.tags.any? %>
          <div class="text-ncs-dark-300 text-sm flex gap-1 flex-wrap">
            <% @skin.tags.each do |tag| %>
              <%= link_to tag.name, skins_gallery_path(tag: tag.name), title: "#{tag.name} - #{tag.taggings_count}" %>
            <% end %>
          </div>
        <% end %>
        <% if @skin.hidden? %>
          <p>
            <%= t "skins.status.hidden.pt1" %>
            <%= link_to t("skins.status.hidden.modlog"), modlog_path(id: @skin.id, type: "Skin"), class: "underline" %>
            <%= t "skins.status.hidden.pt2" %>
          </p>
        <% elsif @skin.is_private? %>
          <p><%= t "skins.status.private" %></p>
        <% elsif @skin.is_unlisted? %>
          <% if !@skin.can_user_open_in_editor?(current_user) %>
            <p><%= t "skins.status.unlisted_guest" %></p>
          <% else %>
            <p><%= t "skins.status.unlisted_owner" %></p>
          <% end %>
        <% end %>
      </div>
      <% if @skin.description.present? %>
        <div class="prose prose-ncs-dark">
          <%= markdown @skin.description %>
        </div>
      <% end %>
      <details class="space-y-2">
        <summary class="select-none cursor-pointer font-bold"><%= t "skins.attributions.self" %></summary>
        <div class="relative">
          <button type="button" class="underline" onclick="copyText('<%= skin_url(@skin) %>', true)">
            Copy Link to this Skin
            <%= heroicon "document-duplicate", class: "inline" %>
          </button>
          <span class="copy-text hidden absolute -top-4 bg-ncs-dark-800 rounded-sm p-0.5 text-ncs-dark-100 text-sm select-none">
            <%= t "actions.copied" %>
          </span>
        </div>
        <fieldset class="border border-ncs-dark-300 p-2 rounded">
          <legend class="font-bold">Attribution</legend>
          <div class="flex gap-2">
            <div id="attribution" class="break-words">
              <%= render partial: "attribution_text", locals: {skin: @skin, attribution: nil, icons: false} %>
            </div>
            <div class="relative">
              <button title="<%= t "actions.copy" %>" onclick="copyText('attribution')">
                <%= heroicon "document-duplicate" %>
              </button>
              <span class="copy-text hidden absolute -top-4 bg-ncs-dark-800 rounded-sm p-0.5 text-ncs-dark-100 text-sm select-none">
                <%= t "actions.copied" %>
              </span>
            </div>
          </div>
        </fieldset>
        <fieldset class="border border-ncs-dark-300 p-2 rounded">
          <legend class="font-bold">Embed Skin</legend>
          <p>Add the following HTML to your site, to embed a preview of this skin. For more info, see
          <%= link_to "the guide", embeds_guide_path, class: "underline", target: "_blank" %>.</p>
          <div class="flex gap-2 mt-1">
            <textarea readonly="true" cols="5" name="embed" id="embed" class="grow resize bg-ncs-dark-800 border-ncs-dark-300" value="">&#60;iframe src="<%= skin_embed_url(@skin) %>" width="200" height="300" style="border: 0px"&#62;&#60;/iframe&#62;</textarea>
            <div class="relative">
              <button title="<%= t "actions.copy" %>" onclick="copyText('embed')">
                <%= heroicon "document-duplicate" %>
              </button>
              <span class="copy-text hidden absolute -top-4 bg-ncs-dark-800 rounded-sm p-0.5 text-ncs-dark-100 text-sm select-none">
                <%= t "actions.copied" %>
              </span>
            </div>
          </div>
        </fieldset>
      </details>
    </div>
    <% if @skin.minecraft_texture_url? || (current_user&.moderator? || @skin.skin_part.can_manually_upload?) %>
      <%= render partial: "give_command", locals: { skin: @skin } %>
    <% end %>
    <% if @skin.user == current_user %>
      <div class="bg-ncs-dark-700 text-ncs-dark-100">
        <div class="bg-ncs-dark-800 p-1">
          <h2>My Stats</h2>
        </div>
        <div class="p-2">
          <p>Total Favourites: <%= @skin.favourites.count %></p>
          <p>Total Downloads: <%= @skin.download_count || 0 %></p>
          <% if @skin.modlogs.any? %>
            <%= link_to "See moderation log", modlog_path(id: @skin.id, type: "Skin"), class: "underline text-ncs-dark-300 text-xs" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @attributions.any? %>
      <div class="bg-ncs-dark-700 text-ncs-dark-100">
        <div class="bg-ncs-dark-800 p-1">
          <h2>Parts Used</h2>
        </div>
        <div class="p-2">
          <div class="flex flex-wrap gap-2 items-start">
            <%= render partial: "attribution", collection: @attributions, as: :attribution %>
          </div>
          <details>
            <summary class="text-sm cursor-pointer select-none">Attribution Text</summary>
            <%= render partial: "attribution_text", collection: @attributions, as: :attribution %>
          </details>
        </div>
      </div>
    <% end %>
    <% if @variants.any? %>
      <div class="bg-ncs-dark-700 text-ncs-dark-100">
        <div class="bg-ncs-dark-800 p-1">
          <h2>Used In</h2>
        </div>
        <div class="p-2">
          <div class="flex flex-wrap gap-2 items-start">
            <%= render partial: "attribution", collection: @variants, as: :attribution, locals: {variant: true} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
  function editSkin(data, attribution, model) {
    localStorage.setItem("ncrs-skin-import", JSON.stringify({
      data: data,
      attribution: attribution,
      model: model,
    }));

    window.location = "/";
  }

  // https://stackoverflow.com/questions/36639681/how-to-copy-text-from-a-div-to-clipboard
  function copyText(id, createText = false) {
    let element;
    if (createText) {
      element = document.createElement('span');
      element.innerText = id;
      document.body.append(element);
    } else {
      element = document.getElementById(id);
    }
    var range = document.createRange();
    range.selectNode(element);
    window.getSelection().removeAllRanges(); // clear current selection
    window.getSelection().addRange(range); // to select text
    document.execCommand("copy");
    window.getSelection().removeAllRanges();// to deselect

    const copied = element.parentElement.querySelector(".copy-text");
    copied.classList.remove("hidden", "hidden-fade");

    if (createText) { element.remove(); }

    setTimeout(() => {
      copied.classList.add("hidden-fade");
    }, 200);
  }
</script>